AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 creada desde GitHub Actions

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite acceso desde Anywhere-IPv4
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0cca150d127c2216f
      InstanceType: t3.micro

      SecurityGroupIds:
        - !Ref MySecurityGroup

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from $(hostname -f) Modeado por A</h1>" > /var/www/html/index.html

      Tags:
        - Key: Name
          Value: EC2-GitHubActions

Outputs:
  InstanceId:
    Value: !Ref MyEC2